name: MarpCLI-GitHub-Actions

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      
jobs:
  marp-to-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set input_dir
        run: |
          while read line;
          do
            echo $line >> $GITHUB_ENV
          done<./config
          
      - name: Create output DIR
        run: |
          mkdir ${{env.DST}}
          chmod 777 -R $_
          
      - name: Export PDF
        run: docker run --rm --init -v "$(pwd):/home/marp/app/"
          -e LANG="ja_JP.UTF-8" -e MARPID="$(id -u):$(id -g)" marpteam/marp-cli ${{env.DIR}}/${{env.RELEASE_VERSION}}.md
          --${{env.FORMAT}}
          -o ${{env.DST}}/${{env.RELEASE_VERSION}}.${{env.FORMAT}}
          --theme ${{env.THEME}}/custom.css
          --html
          --allow-local-files
          
      - name: Create Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{env.DST}}/${{env.RELEASE_VERSION}}.${{env.FORMAT}}, ${{env.DIR}}/${{env.RELEASE_VERSION}}.md
          token: ${{secrets.GITHUB_TOKEN}}
          tag: v${{env.RELEASE_VERSION}}
          name: Release ${{env.RELEASE_VERSION}}
